sudo: false
language: clojure
lein: 2.8.1
install:
  - ./scripts/lein-modules install
script:
  - lein do clean, all test #, all check
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
  - $HOME/.m2
