AWSTemplateFormatVersion: '2010-09-09'

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://crux-cloudformation.s3-eu-west-1.amazonaws.com/crux-cloud/vpc.yml
      Tags:
        - Key: juxt:team
          Value: crux-core

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://crux-cloudformation.s3-eu-west-1.amazonaws.com/crux-cloud/public-lb.yml
      Parameters:
        VPCId: !GetAtt 'VPCStack.Outputs.VPCId'
        PublicSubnetOne: !GetAtt 'VPCStack.Outputs.PublicSubnetOne'
        PublicSubnetTwo: !GetAtt 'VPCStack.Outputs.PublicSubnetTwo'
      Tags:
        - Key: juxt:team
          Value: crux-core
Outputs:
   VPCId:
     Value: !GetAtt 'VPCStack.Outputs.VPCId'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'VPCId' ] ]

   PublicSubnetOne:
     Value: !GetAtt 'VPCStack.Outputs.PublicSubnetOne'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'PublicSubnetOne' ] ]

   PublicSubnetTwo:
     Value: !GetAtt 'VPCStack.Outputs.PublicSubnetTwo'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'PublicSubnetTwo' ] ]

   LoadBalancerSG:
     Value: !GetAtt 'LoadBalancerStack.Outputs.LoadBalancerSG'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LoadBalancerSG' ] ]

   LoadBalancer:
     Value: !GetAtt 'LoadBalancerStack.Outputs.LoadBalancer'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LoadBalancer' ] ]

   LoadBalancerCanonicalHostedZoneId:
     Value: !GetAtt 'LoadBalancerStack.Outputs.LoadBalancerCanonicalHostedZoneId'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LoadBalancerCanonicalHostedZoneId' ] ]

   LoadBalancerDNSName:
     Value: !GetAtt 'LoadBalancerStack.Outputs.LoadBalancerDNSName'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LoadBalancerDNSName' ] ]

   LoadBalancerHTTPSListener:
     Value: !GetAtt 'LoadBalancerStack.Outputs.LoadBalancerHTTPSListener'
     Export:
       Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LoadBalancerHTTPSListener' ] ]
