AWSTemplateFormatVersion: '2010-09-09'
Description: A stack to allow our CI to access our test S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Name of the test S3 bucket

Resources:
  TestS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      LifecycleConfiguration:
        Rules:
          - Id: expire-after-a-day
            ExpirationInDays: 1
            Status: Enabled

  ReadWriteIAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: read-write-crux-test-s3-bucket
      Path: '/crux/'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
            Resource:
              - !Join
                  - ''
                  - - !GetAtt ['TestS3Bucket', 'Arn']
                    - '/*'
